# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/olympus/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/olympus/proprietary/lib/hw/alsa.tegra.so:system/lib/hw/alsa.tegra.so \
    vendor/motorola/olympus/proprietary/lib/hw/audio_policy.tegra.so:system/lib/hw/audio_policy.tegra.so \
    vendor/motorola/olympus/proprietary/lib/hw/audio.primary.tegra.so:system/lib/hw/audio.primary.tegra.so \
    vendor/motorola/olympus/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/motorola/olympus/proprietary/usr/share/alsa/pcm/default.conf:system/usr/share/alsa/pcm/default.conf \
    vendor/motorola/olympus/proprietary/usr/share/alsa/pcm/dmix.conf:system/usr/share/alsa/pcm/dmix.conf \
    vendor/motorola/olympus/proprietary/usr/share/alsa/pcm/dsnoop.conf:system/usr/share/alsa/pcm/dsnoop.conf \
    vendor/motorola/olympus/proprietary/usr/share/alsa/cards/aliases.conf:system/usr/share/alsa/cards/aliases.conf \
    vendor/motorola/olympus/proprietary/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    vendor/motorola/olympus/proprietary/bin/ap_gain.bin:system/bin/ap_gain.bin \
    vendor/motorola/olympus/proprietary/bin/nvcpud:system/bin/nvcpud \
    vendor/motorola/olympus/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/motorola/olympus/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/motorola/olympus/proprietary/lib/hw/vendor-camera.tegra.so:system/lib/hw/vendor-camera.tegra.so \
    vendor/motorola/olympus/proprietary/etc/nvcamera.conf:system/etc/nvcamera.conf \
    vendor/motorola/olympus/proprietary/lib/hw/sensors.olympus.so:system/lib/hw/sensors.olympus.so \
    vendor/motorola/olympus/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/motorola/olympus/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/motorola/olympus/proprietary/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/motorola/olympus/proprietary/etc/nvram.txt:system/etc/nvram.txt \
    vendor/motorola/olympus/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
    vendor/motorola/olympus/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/motorola/olympus/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/motorola/olympus/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/motorola/olympus/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
    vendor/motorola/olympus/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/motorola/olympus/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
    vendor/motorola/olympus/proprietary/lib/libaudio_ext.so:system/lib/libaudio_ext.so \
    vendor/motorola/olympus/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
    vendor/motorola/olympus/proprietary/lib/libnmea.so:system/lib/libnmea.so \
    vendor/motorola/olympus/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/motorola/olympus/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/motorola/olympus/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
    vendor/motorola/olympus/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
    vendor/motorola/olympus/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
    vendor/motorola/olympus/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
    vendor/motorola/olympus/proprietary/lib/libnvos.so:system/lib/libnvos.so \
    vendor/motorola/olympus/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/motorola/olympus/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
    vendor/motorola/olympus/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
    vendor/motorola/olympus/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
    vendor/motorola/olympus/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
    vendor/motorola/olympus/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
    vendor/motorola/olympus/proprietary/lib/libasound.so:system/lib/libasound.so \
    vendor/motorola/olympus/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/motorola/olympus/proprietary/lib/libextdispjni.so:system/lib/libextdispjni.so \
    vendor/motorola/olympus/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/motorola/olympus/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
    vendor/motorola/olympus/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
    vendor/motorola/olympus/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
    vendor/motorola/olympus/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
    vendor/motorola/olympus/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
    vendor/motorola/olympus/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
    vendor/motorola/olympus/proprietary/bin/battd:system/bin/battd \
    vendor/motorola/olympus/proprietary/lib/libbattd.so:system/lib/libbattd.so \
    vendor/motorola/olympus/proprietary/bin/charge_only_mode:system/bin/charge_only_mode \
    vendor/motorola/olympus/proprietary/lib/libmoto_ril.so:system/lib/libmoto_ril.so \
    vendor/motorola/olympus/proprietary/lib/libmoto_mdmctrl.so:system/lib/libmoto_mdmctrl.so \
    vendor/motorola/olympus/proprietary/lib/libpppd_plugin-ril.so:system/lib/libpppd_plugin-ril.so \
    vendor/motorola/olympus/proprietary/lib/librds_util.so:system/lib/librds_util.so \
    vendor/motorola/olympus/proprietary/lib/libril_rds.so:system/lib/libril_rds.so \
    vendor/motorola/olympus/proprietary/bin/pppd-ril:system/bin/pppd-ril \
    vendor/motorola/olympus/proprietary/bin/chat-ril:system/bin/chat-ril \
    vendor/motorola/olympus/proprietary/bin/mdm_panicd:system/bin/mdm_panicd \
    vendor/motorola/olympus/proprietary/etc/ppp/peers/pppd-ril.options:system/etc/ppp/peers/pppd-ril.options \
    vendor/motorola/olympus/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/motorola/olympus/proprietary/etc/firmware/BCM4329B1_002.002.023.0757.0780.hcd:system/etc/firmware/BCM4329B1_002.002.023.0757.0780.hcd \
    vendor/motorola/olympus/proprietary/bin/touchpad:system/bin/touchpad \
    vendor/motorola/olympus/proprietary/bin/whisperd:system/bin/whisperd \
    vendor/motorola/olympus/proprietary/bin/aplogd:system/bin/aplogd \
    vendor/motorola/olympus/proprietary/bin/am2server:system/bin/am2server \
    vendor/motorola/olympus/proprietary/etc/am2server.pubkey:system/etc/am2server.pubkey \
    vendor/motorola/olympus/proprietary/lib/libAuthUDMDrv_1750A100.so:system/lib/libAuthUDMDrv_1750A100.so \
    vendor/motorola/olympus/proprietary/lib/libam2app.so:system/lib/libam2app.so \
    vendor/motorola/olympus/proprietary/lib/libam2server.so:system/lib/libam2server.so \
    vendor/motorola/olympus/proprietary/lib/libnvcpud.so:system/lib/libnvcpud.so \
    vendor/motorola/olympus/proprietary/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
    vendor/motorola/olympus/proprietary/bin/tegrastats:system/proprietary/bin/tegrastats \
    vendor/motorola/olympus/proprietary/lib/hw/audio.a2dp.default.so:system/proprietary/lib/hw/audio.a2dp.default.so \
    vendor/motorola/olympus/proprietary/lib/hw/gralloc.default.so:system/proprietary/lib/hw/gralloc.default.so \
    vendor/motorola/olympus/proprietary/lib/hw/lights.tegra.so:system/proprietary/lib/hw/lights.tegra.so \
    vendor/motorola/olympus/proprietary/lib/hw/nfc.tegra.so:system/proprietary/lib/hw/nfc.tegra.so \
    vendor/motorola/olympus/proprietary/lib/libnvasfparserhal.so:system/proprietary/lib/libnvasfparserhal.so \
    vendor/motorola/olympus/proprietary/lib/libnvaviparserhal.so:system/proprietary/lib/libnvaviparserhal.so \
    vendor/motorola/olympus/proprietary/lib/libnvcap.so:system/proprietary/lib/libnvcap.so \
    vendor/motorola/olympus/proprietary/lib/libnvcap_video.so:system/proprietary/lib/libnvcap_video.so \
    vendor/motorola/olympus/proprietary/lib/libnvcapclk.so:system/proprietary/lib/libnvcapclk.so \
    vendor/motorola/olympus/proprietary/lib/libnvcontrol_jni.so:system/proprietary/lib/libnvcontrol_jni.so \
    vendor/motorola/olympus/proprietary/lib/libnvddk_aes_user.so:system/proprietary/lib/libnvddk_aes_user.so \
    vendor/motorola/olympus/proprietary/lib/libnvhdmi3dplay_jni.so:system/proprietary/lib/libnvhdmi3dplay_jni.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_image.so:system/proprietary/lib/libnvmm_image.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_misc.so:system/proprietary/lib/libnvmm_misc.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_parser.so:system/proprietary/lib/libnvmm_parser.so \
    vendor/motorola/olympus/proprietary/lib/libnvmm_writer.so:system/proprietary/lib/libnvmm_writer.so \
    vendor/motorola/olympus/proprietary/lib/libnvodm_dtvtuner.so:system/proprietary/lib/libnvodm_dtvtuner.so \
    vendor/motorola/olympus/proprietary/lib/libnvodm_hdmi.so:system/proprietary/lib/libnvodm_hdmi.so \
    vendor/motorola/olympus/proprietary/lib/libnvodm_misc.so:system/proprietary/lib/libnvodm_misc.so \
    vendor/motorola/olympus/proprietary/lib/libnvomxadaptor.so:system/proprietary/lib/libnvomxadaptor.so \
    vendor/motorola/olympus/proprietary/lib/libnvparser.so:system/proprietary/lib/libnvparser.so \
    vendor/motorola/olympus/proprietary/lib/libnvsystemuiext_jni.so:system/proprietary/lib/libnvsystemuiext_jni.so \
    vendor/motorola/olympus/proprietary/lib/libnvtestio.so:system/proprietary/lib/libnvtestio.so \
    vendor/motorola/olympus/proprietary/lib/libnvtestresults.so:system/proprietary/lib/libnvtestresults.so \
    vendor/motorola/olympus/proprietary/lib/libvoAndroid.so:system/proprietary/lib/libvoAndroid.so \
    vendor/motorola/olympus/proprietary/lib/libvoConv420To422.so:system/proprietary/lib/libvoConv420To422.so \
    vendor/motorola/olympus/proprietary/lib/libvoMMCCRRS.so:system/proprietary/lib/libvoMMCCRRS.so \
    vendor/motorola/olympus/proprietary/lib/libvoMMPlay.so:system/proprietary/lib/libvoMMPlay.so \
    vendor/motorola/olympus/proprietary/lib/libvoOMXME.so:system/proprietary/lib/libvoOMXME.so \
    vendor/motorola/olympus/proprietary/lib/libvoOMXOne.so:system/proprietary/lib/libvoOMXOne.so \
    vendor/motorola/olympus/proprietary/lib/libvoPackUV.so:system/proprietary/lib/libvoPackUV.so \
    vendor/motorola/olympus/proprietary/lib/libvoRADec.so:system/proprietary/lib/libvoRADec.so \
    vendor/motorola/olympus/proprietary/lib/libvoRealFR.so:system/proprietary/lib/libvoRealFR.so \
    vendor/motorola/olympus/proprietary/lib/libvoRealVideoDec.so:system/proprietary/lib/libvoRealVideoDec.so \
    vendor/motorola/olympus/proprietary/lib/libvoVidDec.so:system/proprietary/lib/libvoVidDec.so \
    vendor/motorola/olympus/proprietary/lib/libvorbisidec.so:system/proprietary/lib/libvorbisidec.so
